[package]
name = "songbox"
version = "0.1.0"
authors = ["Dean Harris <dean@harris.tc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soloud = "0.4.0"